from typing import Any, Dict

class DIContext:
    instances: Dict[type, Any]

    def __init__(self) -> None: ...
    def get(self, interface: type) -> Any: ...
    def set(self, interface: type, instance: Any) -> None: ...
    def clear(self) -> None: ...
